
const discord = require ('discord.js');
var client =  new discord.Client();
const TOKEN = 'NTQ3MzcwNjQ3NzEwNTk3MTIw.D06JNg.IxXixCSJFyGWAcbEbYOqMjA-3Ok'
var colArray = ["https://imgur.com/KmxrVvF",
    "https://imgur.com/kM7tm6L",
    "https://imgur.com/QQnRWth",
    "https://imgur.com/CHQKuyt",
    "https://imgur.com/Lp9w92p",
    "https://imgur.com/gR3G9qX",
    "https://imgur.com/U0eAZos",
    "https://imgur.com/4zUQUXc",
    "https://imgur.com/0NVrRdp",
    "https://imgur.com/fkaJSnK",
    "https://imgur.com/IxYsKFD",
    "https://imgur.com/xMkevHu",
    "https://imgur.com/Ip0RDMu",
    "https://imgur.com/fGz64T0",
    "https://imgur.com/bI5tcdo",


    "https://imgur.com/jCpEWMU",
    "https://imgur.com/YEI22lp",
    "https://imgur.com/IRcWsGP",
    "https://imgur.com/jlw6nBr",
    "https://imgur.com/dxSS5Is",
    "https://imgur.com/vdro9Pm",
    "https://imgur.com/jcxyHal",
    "https://imgur.com/qAy6c82",
    "https://imgur.com/kZtEsuL",
    "https://imgur.com/YLaS54j",
    "https://imgur.com/YLaS54j",
    "https://imgur.com/Z2S67zI",
    "https://imgur.com/utDp1Gu",
    "https://imgur.com/n7HLVyU",
    "https://imgur.com/Fukz71o",

    "https://imgur.com/TlgAAa3",
    "https://imgur.com/WplZYDo",
    "https://imgur.com/4MWu9c1",
    "https://imgur.com/UNsyNro",
    "https://imgur.com/fcd0P2a",
    "https://imgur.com/AjBJGb5",
    "https://imgur.com/Hwr3ZRi",
    "https://imgur.com/wBAoUYT",
    "https://imgur.com/lCZNM06",
    "https://imgur.com/VwiiglQ",
    "https://imgur.com/HrSqGUa",
    "https://imgur.com/NxnylQj",
    "https://imgur.com/PjiJ7Sd",
    "https://imgur.com/EOyh6q2",
    "https://imgur.com/pjcONmT",

    "https://imgur.com/BUkXa8e",
    "https://imgur.com/kSJGpif",
    "https://imgur.com/C5RfFvz",
    "https://imgur.com/6DAltQq",
    "https://imgur.com/dAsGPsm",
    "https://imgur.com/QuwXLtr",
    "https://imgur.com/oJh5jSI",
    "https://imgur.com/ix2sXWp",
    "https://imgur.com/keklu3K",
    "https://imgur.com/2KifiF2",
    "https://imgur.com/CN1SiuW",
    "https://imgur.com/QtRPW8d",
    "https://imgur.com/tdC8Jbx",
    "https://imgur.com/PXEVMXa",
    "https://imgur.com/0FVMPqa",
    
    "https://imgur.com/n6vlTjF",
    "https://imgur.com/1ifmZxA",
    "https://imgur.com/ZBRh2Dq",
    "https://imgur.com/TK8gvhK",
    "https://imgur.com/TBWjnps",
    "https://imgur.com/R1zf98y",
    "https://imgur.com/H9fg7Qi",
    "https://imgur.com/2btXZpA",
    "https://imgur.com/p7kpxhI",
    "https://imgur.com/fi8oFWC",
    "https://imgur.com/nvjVwFV",
    "https://imgur.com/QrPgju9",
    "https://imgur.com/ONHW7Eo",
    "https://imgur.com/WydSTmr",
    "https://imgur.com/pcWclTb",

];

var pageArray = ["https://imgur.com/CUv8Cur",
    "https://imgur.com/O0fQWiv",
    "https://imgur.com/K4IHubP",
    "https://imgur.com/ItMA9oR",
    "https://imgur.com/Z6uXhHG",
    "https://imgur.com/8wt5ck9",
    "https://imgur.com/zIoywKG",
    "https://imgur.com/9cu4sF0",
    "https://imgur.com/j6e7TRX",
    "https://imgur.com/6V1d3lt",
    "https://imgur.com/q7ibDdf",
    "https://imgur.com/KoaqKpZ",
    "https://imgur.com/DsRg8hW",
    "https://imgur.com/IIJROnV",
    "https://imgur.com/b6UA5Sp",
    "https://imgur.com/P2ajYKE",
    "https://imgur.com/dqheBit",
    "https://imgur.com/gzufycu",
    "https://imgur.com/vfsxL6m",
    "https://imgur.com/kfoVJes",
    "https://imgur.com/wnKo047",
    "https://imgur.com/je3cYbm",
    "https://imgur.com/Qdi2zxx",
    "https://imgur.com/PWdgWze",
    "https://imgur.com/3uNrC1J",
    "https://imgur.com/OyNnBMb",
    "https://imgur.com/4CvdrF8",
    "https://imgur.com/Xm7PFGN",
    "https://imgur.com/xxZjdNl",
    "https://imgur.com/Fv7ivkl",
    "https://imgur.com/OivQiz5",
    "https://imgur.com/3ffCPO8",
    "https://imgur.com/QNbYuKg",
    "https://imgur.com/xz3Hhiv",
    "https://imgur.com/lzEFJxq",
    "https://imgur.com/NgSbWqM",
    "https://imgur.com/8xVY2GN",
    "https://imgur.com/ICihH1p",
    "https://imgur.com/66wZCLq",
    "https://imgur.com/SpwzzNP",
    "https://imgur.com/m9uiD79",
    "https://imgur.com/of6x2Ge",
    "https://imgur.com/xprIboz",
    "https://imgur.com/DFvXRk9",
    "https://imgur.com/6vT0s36",
    "https://imgur.com/yMhUXvD",
    "https://imgur.com/kltWDmW",
    "https://imgur.com/XdVGlVn",
    "https://imgur.com/N19gDCc",
    "https://imgur.com/IU3v8DZ",
    "https://imgur.com/mz1YG1y",
    "https://imgur.com/xhjktHn",
    "https://imgur.com/cvhQhw1",
    "https://imgur.com/Bg5RVVI",
    "https://imgur.com/Z2qhYUT",
    "https://imgur.com/02d9sOt",
    "https://imgur.com/3pjiiOl",
    "https://imgur.com/cj27QGE",
    "https://imgur.com/LRnZklo",
    "https://imgur.com/OGKiFZ1",
    "https://imgur.com/0DrDuP9",
    "https://imgur.com/gW7FLPT",
    "https://imgur.com/OdJRX8k",
    "https://imgur.com/Vwl7O5t",
    "https://imgur.com/SVkFXYA",
    "https://imgur.com/P93lVm1",
    "https://imgur.com/58uPCUO",
    "https://imgur.com/ac2ZyDA",
    "https://imgur.com/vkFx3Kp",
    "https://imgur.com/FeEgtc8",
    "https://imgur.com/YYRN283",
    "https://imgur.com/oqK5aSU",
    "https://imgur.com/ltpLyuX",
    "https://imgur.com/iiRhZZt",
    "https://imgur.com/4ZCMveo",
    "https://imgur.com/qJYjmYp",
    "https://imgur.com/QwrNtWZ",
    "https://imgur.com/1IIQhiI",
    "https://imgur.com/1M9dVrL",
    "https://imgur.com/bVmppRG",
    "https://imgur.com/eLltqye",
    "https://imgur.com/PnZYPXU",
    "https://imgur.com/IdwTbae",
    "https://imgur.com/AL0bwVt",
    "https://imgur.com/6azJKgo",
    "https://imgur.com/whUTIUT",
    "https://imgur.com/htCpsRc",
    "https://imgur.com/Kqx6GKq",
    "https://imgur.com/Dq3prd2",
    "https://imgur.com/m7UjQmm",
    "https://imgur.com/NLbhK5O",
    "https://imgur.com/6Yi15Hk",
    "https://imgur.com/GnaMiTw",
    "https://imgur.com/12EViGZ",
    "https://imgur.com/SSwTWR6",
    "https://imgur.com/uBgOgJu",
    "https://imgur.com/KsSHHcv",
    "https://imgur.com/fyZosaC",
    "https://imgur.com/JGPyr79",
    "https://imgur.com/SqQ5tmI",
    "https://imgur.com/NXiDkP4",
    "https://imgur.com/xGFAQxS",
    "https://imgur.com/BRQlouS",
    "https://imgur.com/yipWGSq",
    "https://imgur.com/f98bavg",
    "https://imgur.com/ugwqO4c",
    "https://imgur.com/840EBJu",
    "https://imgur.com/94m6Yw0",
    "https://imgur.com/iGuV0cI",

    "https://imgur.com/lGxFJ9q",
    "https://imgur.com/NqFG2am",
    "https://imgur.com/JH8pAKH",
    "https://imgur.com/M8LSydc",
    "https://imgur.com/OQfneLg",
    "https://imgur.com/e1AsN1y",
    "https://imgur.com/rbdwjk6",
    "https://imgur.com/5nhuCU2",
    "https://imgur.com/fQcmwp1",
    "https://imgur.com/rTqs3Wb",
    "https://imgur.com/9BUjBwJ",
    "https://imgur.com/EHpQSdz",
    "https://imgur.com/RKkisoC",
    "https://imgur.com/w6J8o6A",
    "https://imgur.com/jLSVmqm",
    "https://imgur.com/xKHj4VW",
    "https://imgur.com/E9ucRLl",
    "https://imgur.com/rgo3umS",
    "https://imgur.com/ugeCA9b",
    "https://imgur.com/5kQvbgW",
    "https://imgur.com/wiIlxOk",
    "https://imgur.com/YixdrnM",
    "https://imgur.com/1V3iSDm",
    "https://imgur.com/n09r6oQ",
    "https://imgur.com/GDF4U1l",
    "https://imgur.com/PON7gOA",
    "https://imgur.com/hqAYqxQ",
    "https://imgur.com/YRYBteK",
    "https://imgur.com/C2oIxfx",
    "https://imgur.com/Ox6Z9zl",
    "https://imgur.com/iP7yvin",
    "https://imgur.com/sIFQjf0",
    "https://imgur.com/WiXWREf",
    "https://imgur.com/14ZkJpv",
    "https://imgur.com/poQCC57",
    "https://imgur.com/tYdXiDp",
    "https://imgur.com/Euzb8QF",
    "https://imgur.com/z6rkHP4",
    "https://imgur.com/r7xtFW8",
    "https://imgur.com/q7F9uLM",
    "https://imgur.com/y486jIe",
    "https://imgur.com/lhcLWYx",
    "https://imgur.com/jt6GQaz",
    "https://imgur.com/OHaQf9l",
    "https://imgur.com/TgXZf91",
    "https://imgur.com/bL4yMzP",
    "https://imgur.com/J0iuLfA",
    "https://imgur.com/v4ZTxjd",
    "https://imgur.com/xrWvxIL",
    "https://imgur.com/mGDuQsu",
    "https://imgur.com/OLqNt5M",
    "https://imgur.com/5tlUyKs",
    "https://imgur.com/kGK4Y2T",
    "https://imgur.com/LQNA9Vg",
    "https://imgur.com/n3csnBn",
    "https://imgur.com/z5kwcnq",
    "https://imgur.com/ZVBPKKw",
    "https://imgur.com/QXiwa9U",
    "https://imgur.com/0LgJVRT",
    "https://imgur.com/MD5gpjb",
    "https://imgur.com/dDkKPxo",
    "https://imgur.com/k8hPvTy",
    "https://imgur.com/Q2JkxtY",
    "https://imgur.com/jWwuYlq",
    "https://imgur.com/uLiqHHI",
    "https://imgur.com/Qe5EzzF",
    "https://imgur.com/Hg3it9n",
    "https://imgur.com/P4V2Smh",
    "https://imgur.com/RIbyhiJ",
    "https://imgur.com/JftUVoJ",
    "https://imgur.com/r0yRDX8",
    "https://imgur.com/f86U4rh",
    "https://imgur.com/GnX4yVk",
    "https://imgur.com/uSJYfni",
    "https://imgur.com/RToiEox",
    "https://imgur.com/hhBo5Xi",
    "https://imgur.com/cwB6SfV",
    "https://imgur.com/93oS0JR",
    "https://imgur.com/U55xxLT",
    "https://imgur.com/Cu8BiPb",
    "https://imgur.com/Wy7Q7cf",
    "https://imgur.com/7OCYGOP",
    "https://imgur.com/Lf8I7J7",
    "https://imgur.com/JDkNwT6",
    "https://imgur.com/65RecKL",
    "https://imgur.com/pR1BW2c",
    "https://imgur.com/zi01G4Q",
    "https://imgur.com/l6Dr7lt",
    "https://imgur.com/W0lPDn9",
    "https://imgur.com/m31t8uh",
    "https://imgur.com/fZtHVRZ",
    "https://imgur.com/TeIKKHg",
    "https://imgur.com/DDw0J8L",
    "https://imgur.com/b1Lk5V0",
    "https://imgur.com/HBZYcW0",
    "https://imgur.com/Mk5EhXI",
    "https://imgur.com/ir3xb3U",
    "https://imgur.com/4lQ4BzS",
    "https://imgur.com/z1W3HF1",
    "https://imgur.com/kU3GYfg",
    "https://imgur.com/a27bKty",
    "https://imgur.com/qcAjG9z",
    "https://imgur.com/PWTBZse",
    "https://imgur.com/HDAvvDK",
    "https://imgur.com/eHdTxia",
    "https://imgur.com/EUsQQbU",
    "https://imgur.com/1jLJhCI",
    "https://imgur.com/rnGj45C",
    "https://imgur.com/WV0eLFx",
    "https://imgur.com/sWDamAm",
    "https://imgur.com/1zod5JK",
    
    "https://imgur.com/edN3FOv",
    "https://imgur.com/3hfLDZG",
    "https://imgur.com/Yszh335",
    "https://imgur.com/4tXrIGJ",
    "https://imgur.com/rp3Olb2",
    "https://imgur.com/46LFU1W",
    "https://imgur.com/e3Z36E8",
    "https://imgur.com/q5ldYwe",
    "https://imgur.com/xt4hQfT",
    "https://imgur.com/Bc7oCVP",
    "https://imgur.com/sCkDieW",
    "https://imgur.com/zS8r0ii",
    "https://imgur.com/iD8O76r",
    "https://imgur.com/Hdqs66O",
    "https://imgur.com/hme4nfJ",
    "https://imgur.com/uVhmuJW",
    "https://imgur.com/sPEB2F2",
    "https://imgur.com/Vv37lkW",
    "https://imgur.com/z0ViHQU",
    "https://imgur.com/5prvicP",
    "https://imgur.com/IRwnJSm",
    "https://imgur.com/ZLIqekp",
    "https://imgur.com/s5TpS9Y",
    "https://imgur.com/cFqOtME",
    "https://imgur.com/zgTXnqk",
    "https://imgur.com/A1BVOnQ",
    "https://imgur.com/zlInqL8",
    "https://imgur.com/mFNgsul",
    "https://imgur.com/VlctpOp",
    "https://imgur.com/l1Kob0O",
    "https://imgur.com/pF8DWo6",
    "https://imgur.com/AlhTcbm",
    "https://imgur.com/SFYF4Je",
    "https://imgur.com/C0E3p2J",
    "https://imgur.com/826Qoqm",
    "https://imgur.com/YseMpmN",
    "https://imgur.com/qnGqFCS",
    "https://imgur.com/LUG9UVY",
    "https://imgur.com/DaTEzuH",
    "https://imgur.com/GlAuWFU",
    "https://imgur.com/zon4XcT",
    "https://imgur.com/V9QSyTB",
    "https://imgur.com/UiAvl8H",
    "https://imgur.com/RPurGm4",
    "https://imgur.com/kNSZPZm",
    "https://imgur.com/BthSV2L",
    "https://imgur.com/n5rpvZb",
    "https://imgur.com/KYlQzh8",
    "https://imgur.com/sKvBdO2",
    "https://imgur.com/kRjm7gR",
    "https://imgur.com/TMuzzby",
    "https://imgur.com/SwRaSq2",
    "https://imgur.com/0wzGi2j",
    "https://imgur.com/RAebSEH",
    "https://imgur.com/rHECJu8",
    "https://imgur.com/50RQpjv",
    "https://imgur.com/hJzyrsg",
    "https://imgur.com/uicgd3R",
    "https://imgur.com/WnYktsz",
    "https://imgur.com/xoQ1ovD",
    "https://imgur.com/Wwl5r2N",
    "https://imgur.com/r81BUWI",
    "https://imgur.com/0b04y5s",
    "https://imgur.com/pSCW8W0",
    "https://imgur.com/STIx7St",
    "https://imgur.com/ESKQYUq",
    "https://imgur.com/Qt92w1B",
    "https://imgur.com/zn0viBP",
    "https://imgur.com/HPO2dcV",
    "https://imgur.com/Tl0Ok8R",
    "https://imgur.com/nnIGcwo",
    "https://imgur.com/ZtlbQOi",
    "https://imgur.com/qFJcQGJ",
    "https://imgur.com/dAwsUbI",
    "https://imgur.com/thBDppW",
    "https://imgur.com/UmNi3Cd",
    "https://imgur.com/SYirzZ6",
    "https://imgur.com/WKBE2zo",
    "https://imgur.com/KEnEi0v",
    "https://imgur.com/fvvppE1",
    "https://imgur.com/NKNZk66",
    "https://imgur.com/mg8p8rE",
    "https://imgur.com/hOqDssN",
    "https://imgur.com/FvJejiv",
    "https://imgur.com/YR7S6cs",
    "https://imgur.com/s49eRzm",
    "https://imgur.com/gprlFAi",
    "https://imgur.com/kzEh5U1",
    "https://imgur.com/oGIKMu6",
    "https://imgur.com/AHIxyjN",
    "https://imgur.com/DKQigsh",
    "https://imgur.com/RjjbAHU",
    "https://imgur.com/fGoIT0P",
    "https://imgur.com/u0n5WLz",
    "https://imgur.com/tTlcPLk",
    "https://imgur.com/p8JkTRn",
    "https://imgur.com/Yroj1Wf",
    "https://imgur.com/fD2eRW0",
    "https://imgur.com/WSOw2I2",
    "https://imgur.com/PGrXnuS",
    "https://imgur.com/sNODtpd",
    "https://imgur.com/Sm1FmZ5",
    "https://imgur.com/KNcYgQD",
    "https://imgur.com/RzwJcd1",
    "https://imgur.com/BjbR20b"];

var engArray = ["https://imgur.com/OJzJVNn",
    "https://imgur.com/69LIrfD",
    "https://imgur.com/6NQAuC6",
    "https://imgur.com/dZCSC6D",
    "https://imgur.com/ODSZEZn",
    "https://imgur.com/XelvcSG",
    "https://imgur.com/4v1bicQ",
    "https://imgur.com/vHo4QgI",
    "https://imgur.com/c8qPUag",
    "https://imgur.com/PouuM3A"];

const prefix = "!" 

client.on('ready',() => {
    console.log("Ready");
});

client.on ("message", (message) => {
    if (message.author.bot) return;

    if (message.content.startsWith ("good bot")) {
        message.channel.send ("Thank you! :hearts:")
    }

    if (message.content.startsWith ("Good bot")) {
        message.channel.send ("Thank you! :hearts:")
    }

    if (message.content.startsWith ("bad bot")) {
        message.channel.send ("I'm sorry, I'll do better next time!")
    }

    if (message.content.startsWith ("Bad bot")) {
        message.channel.send ("I'm sorry, I'll do better next time!")
    }

    if (message.content.startsWith (prefix + "help")) {
        message.channel.send ("List of Commands:\n !page for a black-and-white page;\n !color for a color page,\n !eng for an English-translated page;\n !source for a current MEGA link for all DNM+/e+ 4koma/serial manga releases;\n !album for a link to the imgur album for each volume.")
    }
    
    if (message.content.startsWith (prefix + "eng")) { // for translated pages
        message.channel.send ("Hi, " + message.author + ", here you go!")
        var randomPage = Math.floor(Math.random() * engArray.length);
        message.channel.send (engArray[randomPage]);
    }

    if (message.content.startsWith (prefix + "color")) { // for color pages
        message.channel.send ("Hi, " + message.author + ", here you go!")
        var randomPage = Math.floor(Math.random() * colArray.length);
        message.channel.send (colArray[randomPage]);
    }
    
    if (message.content.startsWith (prefix + "page")) { // for regular pages
        message.channel.send ("Hi, " + message.author + ", here you go!")
        var randomPage = Math.floor(Math.random() * pageArray.length);
        message.channel.send (pageArray[randomPage]);
    }

    if (message.content.startsWith (prefix + "source")) {
        message.channel.send (message.author + ", here's the source: https://mega.nz/#F!A2YFmawC!2hgjZRCE4le8VjtjCZr99A")
    }

    if (message.content.startsWith (prefix + "album")) {
        message.channel.send (message.author + ", DNM+ V1: https://imgur.com/a/0HMenNU\n DNM+ V2: https://imgur.com/a/4DCzATq\n DMN+ V3: https://imgur.com/a/UXZHhJN\n DNMe+ V1 (Color only): https://imgur.com/a/MRqCcDr\n DNMe+ V2 (Color only): https://imgur.com/a/BWAr5MI")
    }
    
})

client.login (TOKEN)







